name: Runner CI

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: self-hosted
    steps:
      - run: echo "building"
      - run: sudo executor --dockerfile=gha-runner-with-kaniko/Dockerfile --context=git://github.com/Hi-Fi/image-build-on-managed-app-services.git#refs/heads/custom_image --no-push
